version: '3.8'

services:
  golang-service:
    build:
      context: ./hello-world-go
      dockerfile: Dockerfile
    ports:
      - "9090:8080"
    environment:
      SERVICE_PORT: "9090"
      CLOUD_PROVIDER: "docker"
      CLOUD_REGION: "local"
      CLOUD_ZONE: "local"
      RUNTIME_LANGUAGE: "Golang"

  python-service:
    build:
      context: ./hello-world-python
      dockerfile: Dockerfile
    ports:
      - "9091:8081"
    environment:
      SERVICE_PORT: "9091"
      CLOUD_PROVIDER: "docker"
      CLOUD_REGION: "local"
      CLOUD_ZONE: "local"
      RUNTIME_LANGUAGE: "Python"

  csharp-service:
    build:
      context: ./hello-world-csharp
      dockerfile: Dockerfile
    ports:
      - "9092:8082"
    environment:
      SERVICE_PORT: "9092"
      CLOUD_PROVIDER: "docker"
      CLOUD_REGION: "local"
      CLOUD_ZONE: "local"
      RUNTIME_LANGUAGE: "C#"
